"""create platform schema

Revision ID: c4b54eb504cc
Revises: 
Create Date: 2026-08-18 13:33:51.913197

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c4b54eb504cc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'VIEWER', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('KYC_REVIEW', 'REFUND', 'FEATURE_FLAG', 'USER', name='auditentity', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'STATUS_CHANGED', 'ASSIGNED', 'NOTE_ADDED', 'TOGGLED', 'DELETED', name='auditaction', native_enum=False), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_key'), ['key'], unique=True)

    op.create_table('kyc_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_reference', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_country', sa.String(length=2), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'ESCALATED', name='kycstatus', native_enum=False), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False), nullable=False),
    sa.Column('risk_summary', sa.Text(), nullable=False),
    sa.Column('sanctions_hit', sa.Boolean(), nullable=False),
    sa.Column('pep_match', sa.Boolean(), nullable=False),
    sa.Column('primary_document_type', sa.Enum('PASSPORT', 'DRIVERS_LICENSE', 'NATIONAL_ID', 'PROOF_OF_ADDRESS', 'BUSINESS_REGISTRATION', name='documenttype', native_enum=False), nullable=False),
    sa.Column('assigned_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_reviews_assigned_reviewer_id'), ['assigned_reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_reviews_case_reference'), ['case_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_kyc_reviews_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_reviews_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_reviews_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_reference', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('transaction_reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Enum('DUPLICATE_CHARGE', 'SERVICE_NOT_RENDERED', 'FRAUD', 'CUSTOMER_REQUEST', 'PROCESSING_ERROR', name='refundreason', native_enum=False), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'INFO_REQUESTED', name='refundstatus', native_enum=False), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_refund_reference'), ['refund_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_refunds_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_status'), ['status'], unique=False)

    op.create_table('feature_flag_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.Enum('PRODUCTION', 'STAGING', 'DEVELOPMENT', name='flagenvironment', native_enum=False), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rollout_percentage >= 0 AND rollout_percentage <= 100', name='ck_rollout_percentage_range'),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag_id', 'environment', name='uq_flag_environment')
    )
    with op.batch_alter_table('feature_flag_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flag_states_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_flag_states_flag_id'), ['flag_id'], unique=False)

    op.create_table('kyc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('PASSPORT', 'DRIVERS_LICENSE', 'NATIONAL_ID', 'PROOF_OF_ADDRESS', 'BUSINESS_REGISTRATION', name='documenttype', native_enum=False), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['kyc_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_documents_review_id'), ['review_id'], unique=False)

    op.create_table('kyc_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['kyc_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_notes_review_id'), ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kyc_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_notes_review_id'))

    op.drop_table('kyc_notes')
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_documents_review_id'))

    op.drop_table('kyc_documents')
    with op.batch_alter_table('feature_flag_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flag_states_flag_id'))
        batch_op.drop_index(batch_op.f('ix_feature_flag_states_environment'))

    op.drop_table('feature_flag_states')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_status'))
        batch_op.drop_index(batch_op.f('ix_refunds_requested_at'))
        batch_op.drop_index(batch_op.f('ix_refunds_refund_reference'))
        batch_op.drop_index(batch_op.f('ix_refunds_reason'))
        batch_op.drop_index(batch_op.f('ix_refunds_customer_name'))
        batch_op.drop_index(batch_op.f('ix_refunds_amount'))

    op.drop_table('refunds')
    with op.batch_alter_table('kyc_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_reviews_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_kyc_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_kyc_reviews_risk_level'))
        batch_op.drop_index(batch_op.f('ix_kyc_reviews_customer_name'))
        batch_op.drop_index(batch_op.f('ix_kyc_reviews_case_reference'))
        batch_op.drop_index(batch_op.f('ix_kyc_reviews_assigned_reviewer_id'))

    op.drop_table('kyc_reviews')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_key'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
